/*
 * ==========================================
 * |          GENERATED BY SUPAZOD          |
 * ==========================================
 */

import { z } from "zod";
/** Recursive JSON (aligned with `Database["public"]["Views"]` Json columns). Patched after supazod. */
type JsonLike =
  | string
  | number
  | boolean
  | null
  | { [key: string]: JsonLike | undefined }
  | JsonLike[];



export const publicAlertFrequencySchema = z.union([
  z.literal("instant"),
  z.literal("daily"),
  z.literal("weekly"),
]);

export const publicApplicationStatusSchema = z.union([
  z.literal("pending"),
  z.literal("reviewed"),
  z.literal("shortlisted"),
  z.literal("rejected"),
  z.literal("withdrawn"),
]);

export const publicCompanyRoleSchema = z.union([
  z.literal("owner"),
  z.literal("admin"),
  z.literal("member"),
]);

export const publicEntityTypeSchema = z.union([
  z.literal("user"),
  z.literal("company"),
]);

export const publicJobStatusSchema = z.union([
  z.literal("draft"),
  z.literal("published"),
  z.literal("archived"),
]);

export const publicUserRoleSchema = z.union([
  z.literal("user"),
  z.literal("employer"),
  z.literal("premium_employer"),
  z.literal("admin"),
]);

export const jsonSchema: z.ZodType<JsonLike | null> = z.lazy(() =>
  z
    .union([
      z.string(),
      z.number(),
      z.boolean(),
      z.record(z.string(), z.union([jsonSchema, z.undefined()])),
      z.array(jsonSchema),
    ])
    .nullable(),
);

export const publicAlertsRowSchema = z.object({
  archived_at: z.string().nullable(),
  created_at: z.string(),
  filters: jsonSchema,
  frequency: publicAlertFrequencySchema,
  id: z.string(),
  is_active: z.boolean(),
  is_archived: z.boolean(),
  last_sent_at: z.string().nullable(),
  name: z.string(),
  user_id: z.string(),
});

export const publicAlertsInsertSchema = z.object({
  archived_at: z.string().optional().nullable(),
  created_at: z.string().optional(),
  filters: jsonSchema.optional(),
  frequency: publicAlertFrequencySchema.optional(),
  id: z.string().optional(),
  is_active: z.boolean().optional(),
  is_archived: z.boolean().optional(),
  last_sent_at: z.string().optional().nullable(),
  name: z.string(),
  user_id: z.string(),
});

export const publicAlertsUpdateSchema = z.object({
  archived_at: z.string().optional().nullable(),
  created_at: z.string().optional(),
  filters: jsonSchema.optional(),
  frequency: publicAlertFrequencySchema.optional(),
  id: z.string().optional(),
  is_active: z.boolean().optional(),
  is_archived: z.boolean().optional(),
  last_sent_at: z.string().optional().nullable(),
  name: z.string().optional(),
  user_id: z.string().optional(),
});

export const publicAppReleaseAnnouncementsRowSchema = z.object({
  body_html: z.string(),
  created_at: z.string(),
  created_by: z.string().nullable(),
  draft: z.boolean(),
  id: z.string(),
  sent_at: z.string().nullable(),
  title: z.string(),
  version: z.string(),
});

export const publicAppReleaseAnnouncementsInsertSchema = z.object({
  body_html: z.string().optional(),
  created_at: z.string().optional(),
  created_by: z.string().optional().nullable(),
  draft: z.boolean().optional(),
  id: z.string().optional(),
  sent_at: z.string().optional().nullable(),
  title: z.string(),
  version: z.string(),
});

export const publicAppReleaseAnnouncementsUpdateSchema = z.object({
  body_html: z.string().optional(),
  created_at: z.string().optional(),
  created_by: z.string().optional().nullable(),
  draft: z.boolean().optional(),
  id: z.string().optional(),
  sent_at: z.string().optional().nullable(),
  title: z.string().optional(),
  version: z.string().optional(),
});

export const publicAppStateRowSchema = z.object({
  key: z.string(),
  value: z.string().nullable(),
});

export const publicAppStateInsertSchema = z.object({
  key: z.string(),
  value: z.string().optional().nullable(),
});

export const publicAppStateUpdateSchema = z.object({
  key: z.string().optional(),
  value: z.string().optional().nullable(),
});

export const publicApplicationsRowSchema = z.object({
  applied_at: z.string(),
  archived_at: z.string().nullable(),
  cv_url: z.string().nullable(),
  form_data: jsonSchema.nullable(),
  id: z.string(),
  is_archived: z.boolean(),
  job_id: z.string(),
  status: publicApplicationStatusSchema,
  updated_at: z.string(),
  user_id: z.string(),
  withdraw_reason: z.string().nullable(),
  withdrawn_at: z.string().nullable(),
});

export const publicApplicationsInsertSchema = z.object({
  applied_at: z.string().optional(),
  archived_at: z.string().optional().nullable(),
  cv_url: z.string().optional().nullable(),
  form_data: jsonSchema.optional().nullable(),
  id: z.string().optional(),
  is_archived: z.boolean().optional(),
  job_id: z.string(),
  status: publicApplicationStatusSchema.optional(),
  updated_at: z.string().optional(),
  user_id: z.string(),
  withdraw_reason: z.string().optional().nullable(),
  withdrawn_at: z.string().optional().nullable(),
});

export const publicApplicationsUpdateSchema = z.object({
  applied_at: z.string().optional(),
  archived_at: z.string().optional().nullable(),
  cv_url: z.string().optional().nullable(),
  form_data: jsonSchema.optional().nullable(),
  id: z.string().optional(),
  is_archived: z.boolean().optional(),
  job_id: z.string().optional(),
  status: publicApplicationStatusSchema.optional(),
  updated_at: z.string().optional(),
  user_id: z.string().optional(),
  withdraw_reason: z.string().optional().nullable(),
  withdrawn_at: z.string().optional().nullable(),
});

export const publicApplicationsRelationshipsSchema = z.tuple([
  z.object({
    foreignKeyName: z.literal("applications_job_id_fkey"),
    columns: z.tuple([z.literal("job_id")]),
    isOneToOne: z.literal(false),
    referencedRelation: z.literal("job_listings"),
    referencedColumns: z.tuple([z.literal("id")]),
  }),
]);

export const publicBlogPostsRowSchema = z.object({
  author_id: z.string().nullable(),
  canonical_url: z.string().nullable(),
  content_markdown: z.string(),
  cover_image_url: z.string().nullable(),
  created_at: z.string(),
  excerpt: z.string().nullable(),
  id: z.string(),
  notified_at: z.string().nullable(),
  published_at: z.string().nullable(),
  reading_time_minutes: z.number().nullable(),
  seo_description: z.string().nullable(),
  seo_title: z.string().nullable(),
  slug: z.string(),
  status: z.string(),
  tags: z.array(z.string()),
  title: z.string(),
  updated_at: z.string(),
});

export const publicBlogPostsInsertSchema = z.object({
  author_id: z.string().optional().nullable(),
  canonical_url: z.string().optional().nullable(),
  content_markdown: z.string(),
  cover_image_url: z.string().optional().nullable(),
  created_at: z.string().optional(),
  excerpt: z.string().optional().nullable(),
  id: z.string().optional(),
  notified_at: z.string().optional().nullable(),
  published_at: z.string().optional().nullable(),
  reading_time_minutes: z.number().optional().nullable(),
  seo_description: z.string().optional().nullable(),
  seo_title: z.string().optional().nullable(),
  slug: z.string(),
  status: z.string().optional(),
  tags: z.array(z.string()).optional(),
  title: z.string(),
  updated_at: z.string().optional(),
});

export const publicBlogPostsUpdateSchema = z.object({
  author_id: z.string().optional().nullable(),
  canonical_url: z.string().optional().nullable(),
  content_markdown: z.string().optional(),
  cover_image_url: z.string().optional().nullable(),
  created_at: z.string().optional(),
  excerpt: z.string().optional().nullable(),
  id: z.string().optional(),
  notified_at: z.string().optional().nullable(),
  published_at: z.string().optional().nullable(),
  reading_time_minutes: z.number().optional().nullable(),
  seo_description: z.string().optional().nullable(),
  seo_title: z.string().optional().nullable(),
  slug: z.string().optional(),
  status: z.string().optional(),
  tags: z.array(z.string()).optional(),
  title: z.string().optional(),
  updated_at: z.string().optional(),
});

export const publicBlogPostsRelationshipsSchema = z.tuple([
  z.object({
    foreignKeyName: z.literal("blog_posts_author_id_fkey"),
    columns: z.tuple([z.literal("author_id")]),
    isOneToOne: z.literal(false),
    referencedRelation: z.literal("profiles"),
    referencedColumns: z.tuple([z.literal("id")]),
  }),
]);

export const publicCompaniesRowSchema = z.object({
  archived_at: z.string().nullable(),
  claimed_at: z.string().nullable(),
  claimed_by: z.string().nullable(),
  created_at: z.string(),
  created_by: z.string().nullable(),
  description: z.string().nullable(),
  email: z.string().nullable(),
  engages: z.number(),
  founded_year: z.number().nullable(),
  id: z.string(),
  industry: z.string().nullable(),
  is_archived: z.boolean(),
  is_claimed: z.boolean(),
  location: z.string().nullable(),
  logo_url: z.string().nullable(),
  name: z.string(),
  size: z.string().nullable(),
  slug: z.string(),
  updated_at: z.string(),
  visits: z.number(),
  website: z.string().nullable(),
});

export const publicCompaniesInsertSchema = z.object({
  archived_at: z.string().optional().nullable(),
  claimed_at: z.string().optional().nullable(),
  claimed_by: z.string().optional().nullable(),
  created_at: z.string().optional(),
  created_by: z.string().optional().nullable(),
  description: z.string().optional().nullable(),
  email: z.string().optional().nullable(),
  engages: z.number().optional(),
  founded_year: z.number().optional().nullable(),
  id: z.string().optional(),
  industry: z.string().optional().nullable(),
  is_archived: z.boolean().optional(),
  is_claimed: z.boolean().optional(),
  location: z.string().optional().nullable(),
  logo_url: z.string().optional().nullable(),
  name: z.string(),
  size: z.string().optional().nullable(),
  slug: z.string(),
  updated_at: z.string().optional(),
  visits: z.number().optional(),
  website: z.string().optional().nullable(),
});

export const publicCompaniesUpdateSchema = z.object({
  archived_at: z.string().optional().nullable(),
  claimed_at: z.string().optional().nullable(),
  claimed_by: z.string().optional().nullable(),
  created_at: z.string().optional(),
  created_by: z.string().optional().nullable(),
  description: z.string().optional().nullable(),
  email: z.string().optional().nullable(),
  engages: z.number().optional(),
  founded_year: z.number().optional().nullable(),
  id: z.string().optional(),
  industry: z.string().optional().nullable(),
  is_archived: z.boolean().optional(),
  is_claimed: z.boolean().optional(),
  location: z.string().optional().nullable(),
  logo_url: z.string().optional().nullable(),
  name: z.string().optional(),
  size: z.string().optional().nullable(),
  slug: z.string().optional(),
  updated_at: z.string().optional(),
  visits: z.number().optional(),
  website: z.string().optional().nullable(),
});

export const publicCompanyClaimNudgeLogRowSchema = z.object({
  company_id: z.string().nullable(),
  id: z.string(),
  sent_at: z.string(),
  sent_to: z.string().nullable(),
  status: z.string(),
});

export const publicCompanyClaimNudgeLogInsertSchema = z.object({
  company_id: z.string().optional().nullable(),
  id: z.string().optional(),
  sent_at: z.string().optional(),
  sent_to: z.string().optional().nullable(),
  status: z.string().optional(),
});

export const publicCompanyClaimNudgeLogUpdateSchema = z.object({
  company_id: z.string().optional().nullable(),
  id: z.string().optional(),
  sent_at: z.string().optional(),
  sent_to: z.string().optional().nullable(),
  status: z.string().optional(),
});

export const publicCompanyClaimNudgeLogRelationshipsSchema = z.tuple([
  z.object({
    foreignKeyName: z.literal("company_claim_nudge_log_company_id_fkey"),
    columns: z.tuple([z.literal("company_id")]),
    isOneToOne: z.literal(false),
    referencedRelation: z.literal("companies"),
    referencedColumns: z.tuple([z.literal("id")]),
  }),
]);

export const publicCompanyClaimTokensRowSchema = z.object({
  code_hash: z.string(),
  company_id: z.string(),
  consumed_at: z.string().nullable(),
  created_at: z.string(),
  expires_at: z.string(),
  failed_attempts: z.number(),
  last_attempt_at: z.string().nullable(),
  token: z.string(),
});

export const publicCompanyClaimTokensInsertSchema = z.object({
  code_hash: z.string(),
  company_id: z.string(),
  consumed_at: z.string().optional().nullable(),
  created_at: z.string().optional(),
  expires_at: z.string().optional(),
  failed_attempts: z.number().optional(),
  last_attempt_at: z.string().optional().nullable(),
  token: z.string().optional(),
});

export const publicCompanyClaimTokensUpdateSchema = z.object({
  code_hash: z.string().optional(),
  company_id: z.string().optional(),
  consumed_at: z.string().optional().nullable(),
  created_at: z.string().optional(),
  expires_at: z.string().optional(),
  failed_attempts: z.number().optional(),
  last_attempt_at: z.string().optional().nullable(),
  token: z.string().optional(),
});

export const publicCompanyClaimTokensRelationshipsSchema = z.tuple([
  z.object({
    foreignKeyName: z.literal("company_claim_tokens_company_id_fkey"),
    columns: z.tuple([z.literal("company_id")]),
    isOneToOne: z.literal(true),
    referencedRelation: z.literal("companies"),
    referencedColumns: z.tuple([z.literal("id")]),
  }),
]);

export const publicCompanyFavouritesRowSchema = z.object({
  company_id: z.string(),
  created_at: z.string(),
  user_id: z.string(),
});

export const publicCompanyFavouritesInsertSchema = z.object({
  company_id: z.string(),
  created_at: z.string().optional(),
  user_id: z.string(),
});

export const publicCompanyFavouritesUpdateSchema = z.object({
  company_id: z.string().optional(),
  created_at: z.string().optional(),
  user_id: z.string().optional(),
});

export const publicCompanyFavouritesRelationshipsSchema = z.tuple([
  z.object({
    foreignKeyName: z.literal("company_favourites_company_id_fkey"),
    columns: z.tuple([z.literal("company_id")]),
    isOneToOne: z.literal(false),
    referencedRelation: z.literal("companies"),
    referencedColumns: z.tuple([z.literal("id")]),
  }),
]);

export const publicCompanySkillsRowSchema = z.object({
  company_id: z.string(),
  created_at: z.string(),
  id: z.string(),
  skill_id: z.string(),
  sort_order: z.number(),
});

export const publicCompanySkillsInsertSchema = z.object({
  company_id: z.string(),
  created_at: z.string().optional(),
  id: z.string().optional(),
  skill_id: z.string(),
  sort_order: z.number().optional(),
});

export const publicCompanySkillsUpdateSchema = z.object({
  company_id: z.string().optional(),
  created_at: z.string().optional(),
  id: z.string().optional(),
  skill_id: z.string().optional(),
  sort_order: z.number().optional(),
});

export const publicCompanySkillsRelationshipsSchema = z.tuple([
  z.object({
    foreignKeyName: z.literal("company_skills_company_id_fkey"),
    columns: z.tuple([z.literal("company_id")]),
    isOneToOne: z.literal(false),
    referencedRelation: z.literal("companies"),
    referencedColumns: z.tuple([z.literal("id")]),
  }),
  z.object({
    foreignKeyName: z.literal("company_skills_skill_id_fkey"),
    columns: z.tuple([z.literal("skill_id")]),
    isOneToOne: z.literal(false),
    referencedRelation: z.literal("skills"),
    referencedColumns: z.tuple([z.literal("id")]),
  }),
]);

export const publicCompanyUsersRowSchema = z.object({
  accepted_at: z.string().nullable(),
  company_id: z.string(),
  invited_at: z.string(),
  role: publicCompanyRoleSchema,
  user_id: z.string(),
});

export const publicCompanyUsersInsertSchema = z.object({
  accepted_at: z.string().optional().nullable(),
  company_id: z.string(),
  invited_at: z.string().optional(),
  role: publicCompanyRoleSchema.optional(),
  user_id: z.string(),
});

export const publicCompanyUsersUpdateSchema = z.object({
  accepted_at: z.string().optional().nullable(),
  company_id: z.string().optional(),
  invited_at: z.string().optional(),
  role: publicCompanyRoleSchema.optional(),
  user_id: z.string().optional(),
});

export const publicCompanyUsersRelationshipsSchema = z.tuple([
  z.object({
    foreignKeyName: z.literal("company_users_company_id_fkey"),
    columns: z.tuple([z.literal("company_id")]),
    isOneToOne: z.literal(false),
    referencedRelation: z.literal("companies"),
    referencedColumns: z.tuple([z.literal("id")]),
  }),
]);

export const publicContactInfoRowSchema = z.object({
  email: z.string().nullable(),
  entity_id: z.string(),
  entity_type: publicEntityTypeSchema,
  id: z.string(),
  linkedin: z.string().nullable(),
  phone: z.string().nullable(),
  website: z.string().nullable(),
});

export const publicContactInfoInsertSchema = z.object({
  email: z.string().optional().nullable(),
  entity_id: z.string(),
  entity_type: publicEntityTypeSchema,
  id: z.string().optional(),
  linkedin: z.string().optional().nullable(),
  phone: z.string().optional().nullable(),
  website: z.string().optional().nullable(),
});

export const publicContactInfoUpdateSchema = z.object({
  email: z.string().optional().nullable(),
  entity_id: z.string().optional(),
  entity_type: publicEntityTypeSchema.optional(),
  id: z.string().optional(),
  linkedin: z.string().optional().nullable(),
  phone: z.string().optional().nullable(),
  website: z.string().optional().nullable(),
});

export const publicConversationParticipantsRowSchema = z.object({
  conversation_id: z.string(),
  user_id: z.string(),
});

export const publicConversationParticipantsInsertSchema = z.object({
  conversation_id: z.string(),
  user_id: z.string(),
});

export const publicConversationParticipantsUpdateSchema = z.object({
  conversation_id: z.string().optional(),
  user_id: z.string().optional(),
});

export const publicConversationParticipantsRelationshipsSchema = z.tuple([
  z.object({
    foreignKeyName: z.literal("conversation_participants_conversation_id_fkey"),
    columns: z.tuple([z.literal("conversation_id")]),
    isOneToOne: z.literal(false),
    referencedRelation: z.literal("conversations"),
    referencedColumns: z.tuple([z.literal("id")]),
  }),
]);

export const publicConversationsRowSchema = z.object({
  created_at: z.string(),
  id: z.string(),
});

export const publicConversationsInsertSchema = z.object({
  created_at: z.string().optional(),
  id: z.string().optional(),
});

export const publicConversationsUpdateSchema = z.object({
  created_at: z.string().optional(),
  id: z.string().optional(),
});

export const publicFaqRowSchema = z.object({
  answer: z.string(),
  created_at: z.string(),
  id: z.string(),
  is_active: z.boolean(),
  placement: z.string(),
  question: z.string(),
  sort_order: z.number(),
  updated_at: z.string(),
});

export const publicFaqInsertSchema = z.object({
  answer: z.string(),
  created_at: z.string().optional(),
  id: z.string().optional(),
  is_active: z.boolean().optional(),
  placement: z.string(),
  question: z.string(),
  sort_order: z.number().optional(),
  updated_at: z.string().optional(),
});

export const publicFaqUpdateSchema = z.object({
  answer: z.string().optional(),
  created_at: z.string().optional(),
  id: z.string().optional(),
  is_active: z.boolean().optional(),
  placement: z.string().optional(),
  question: z.string().optional(),
  sort_order: z.number().optional(),
  updated_at: z.string().optional(),
});

export const publicFavoritesRowSchema = z.object({
  created_at: z.string(),
  job_id: z.string(),
  user_id: z.string(),
});

export const publicFavoritesInsertSchema = z.object({
  created_at: z.string().optional(),
  job_id: z.string(),
  user_id: z.string(),
});

export const publicFavoritesUpdateSchema = z.object({
  created_at: z.string().optional(),
  job_id: z.string().optional(),
  user_id: z.string().optional(),
});

export const publicFavoritesRelationshipsSchema = z.tuple([
  z.object({
    foreignKeyName: z.literal("favorites_job_id_fkey"),
    columns: z.tuple([z.literal("job_id")]),
    isOneToOne: z.literal(false),
    referencedRelation: z.literal("job_listings"),
    referencedColumns: z.tuple([z.literal("id")]),
  }),
]);

export const publicFormFieldsRowSchema = z.object({
  field_type: z.string(),
  form_id: z.string(),
  id: z.string(),
  is_required: z.boolean(),
  label: z.string(),
  options: jsonSchema.nullable(),
  placeholder: z.string().nullable(),
  sort_order: z.number(),
});

export const publicFormFieldsInsertSchema = z.object({
  field_type: z.string(),
  form_id: z.string(),
  id: z.string().optional(),
  is_required: z.boolean().optional(),
  label: z.string(),
  options: jsonSchema.optional().nullable(),
  placeholder: z.string().optional().nullable(),
  sort_order: z.number(),
});

export const publicFormFieldsUpdateSchema = z.object({
  field_type: z.string().optional(),
  form_id: z.string().optional(),
  id: z.string().optional(),
  is_required: z.boolean().optional(),
  label: z.string().optional(),
  options: jsonSchema.optional().nullable(),
  placeholder: z.string().optional().nullable(),
  sort_order: z.number().optional(),
});

export const publicFormFieldsRelationshipsSchema = z.tuple([
  z.object({
    foreignKeyName: z.literal("form_fields_form_id_fkey"),
    columns: z.tuple([z.literal("form_id")]),
    isOneToOne: z.literal(false),
    referencedRelation: z.literal("forms"),
    referencedColumns: z.tuple([z.literal("id")]),
  }),
]);

export const publicFormResponseValuesRowSchema = z.object({
  field_id: z.string(),
  id: z.string(),
  response_id: z.string(),
  value: z.string().nullable(),
});

export const publicFormResponseValuesInsertSchema = z.object({
  field_id: z.string(),
  id: z.string().optional(),
  response_id: z.string(),
  value: z.string().optional().nullable(),
});

export const publicFormResponseValuesUpdateSchema = z.object({
  field_id: z.string().optional(),
  id: z.string().optional(),
  response_id: z.string().optional(),
  value: z.string().optional().nullable(),
});

export const publicFormResponseValuesRelationshipsSchema = z.tuple([
  z.object({
    foreignKeyName: z.literal("form_response_values_field_id_fkey"),
    columns: z.tuple([z.literal("field_id")]),
    isOneToOne: z.literal(false),
    referencedRelation: z.literal("form_fields"),
    referencedColumns: z.tuple([z.literal("id")]),
  }),
  z.object({
    foreignKeyName: z.literal("form_response_values_response_id_fkey"),
    columns: z.tuple([z.literal("response_id")]),
    isOneToOne: z.literal(false),
    referencedRelation: z.literal("form_responses"),
    referencedColumns: z.tuple([z.literal("id")]),
  }),
]);

export const publicFormResponsesRowSchema = z.object({
  created_at: z.string(),
  form_id: z.string(),
  id: z.string(),
  job_listing_id: z.string().nullable(),
  respondent_email: z.string().nullable(),
  respondent_name: z.string().nullable(),
});

export const publicFormResponsesInsertSchema = z.object({
  created_at: z.string().optional(),
  form_id: z.string(),
  id: z.string().optional(),
  job_listing_id: z.string().optional().nullable(),
  respondent_email: z.string().optional().nullable(),
  respondent_name: z.string().optional().nullable(),
});

export const publicFormResponsesUpdateSchema = z.object({
  created_at: z.string().optional(),
  form_id: z.string().optional(),
  id: z.string().optional(),
  job_listing_id: z.string().optional().nullable(),
  respondent_email: z.string().optional().nullable(),
  respondent_name: z.string().optional().nullable(),
});

export const publicFormResponsesRelationshipsSchema = z.tuple([
  z.object({
    foreignKeyName: z.literal("form_responses_form_id_fkey"),
    columns: z.tuple([z.literal("form_id")]),
    isOneToOne: z.literal(false),
    referencedRelation: z.literal("forms"),
    referencedColumns: z.tuple([z.literal("id")]),
  }),
  z.object({
    foreignKeyName: z.literal("form_responses_job_listing_id_fkey"),
    columns: z.tuple([z.literal("job_listing_id")]),
    isOneToOne: z.literal(false),
    referencedRelation: z.literal("job_listings"),
    referencedColumns: z.tuple([z.literal("id")]),
  }),
]);

export const publicFormsRowSchema = z.object({
  archived_at: z.string().nullable(),
  company_id: z.string(),
  created_at: z.string(),
  description: z.string().nullable(),
  id: z.string(),
  is_archived: z.boolean(),
  name: z.string(),
  status: z.string(),
});

export const publicFormsInsertSchema = z.object({
  archived_at: z.string().optional().nullable(),
  company_id: z.string(),
  created_at: z.string().optional(),
  description: z.string().optional().nullable(),
  id: z.string().optional(),
  is_archived: z.boolean().optional(),
  name: z.string(),
  status: z.string().optional(),
});

export const publicFormsUpdateSchema = z.object({
  archived_at: z.string().optional().nullable(),
  company_id: z.string().optional(),
  created_at: z.string().optional(),
  description: z.string().optional().nullable(),
  id: z.string().optional(),
  is_archived: z.boolean().optional(),
  name: z.string().optional(),
  status: z.string().optional(),
});

export const publicFormsRelationshipsSchema = z.tuple([
  z.object({
    foreignKeyName: z.literal("forms_company_id_fkey"),
    columns: z.tuple([z.literal("company_id")]),
    isOneToOne: z.literal(false),
    referencedRelation: z.literal("companies"),
    referencedColumns: z.tuple([z.literal("id")]),
  }),
]);

export const publicJobBenefitsRowSchema = z.object({
  created_at: z.string().nullable(),
  id: z.string(),
  job_id: z.string(),
  sort_order: z.number(),
  title: z.string(),
});

export const publicJobBenefitsInsertSchema = z.object({
  created_at: z.string().optional().nullable(),
  id: z.string().optional(),
  job_id: z.string(),
  sort_order: z.number().optional(),
  title: z.string(),
});

export const publicJobBenefitsUpdateSchema = z.object({
  created_at: z.string().optional().nullable(),
  id: z.string().optional(),
  job_id: z.string().optional(),
  sort_order: z.number().optional(),
  title: z.string().optional(),
});

export const publicJobBenefitsRelationshipsSchema = z.tuple([
  z.object({
    foreignKeyName: z.literal("job_benefits_job_id_fkey"),
    columns: z.tuple([z.literal("job_id")]),
    isOneToOne: z.literal(false),
    referencedRelation: z.literal("job_listings"),
    referencedColumns: z.tuple([z.literal("id")]),
  }),
]);

export const publicJobListingsRowSchema = z.object({
  application_form_id: z.string().nullable(),
  application_url: z.string().nullable(),
  applications_count: z.number(),
  archived_at: z.string().nullable(),
  benefits_count: z.number(),
  company_id: z.string(),
  created_at: z.string(),
  description: z.string().nullable(),
  experience_level: z.array(z.string()).nullable(),
  expires_at: z.string().nullable(),
  id: z.string(),
  is_archived: z.boolean(),
  is_external: z.boolean(),
  is_remote: z.boolean(),
  job_type: z.string().nullable(),
  location: z.string().nullable(),
  published_at: z.string().nullable(),
  salary_currency: z.string().nullable(),
  salary_max: z.number().nullable(),
  salary_min: z.number().nullable(),
  search_vector: z.unknown(),
  slug: z.string(),
  source_hash: z.string().nullable(),
  source_url: z.string().nullable(),
  status: publicJobStatusSchema,
  title: z.string(),
  updated_at: z.string(),
});

export const publicJobListingsInsertSchema = z.object({
  application_form_id: z.string().optional().nullable(),
  application_url: z.string().optional().nullable(),
  applications_count: z.number().optional(),
  archived_at: z.string().optional().nullable(),
  benefits_count: z.number().optional(),
  company_id: z.string(),
  created_at: z.string().optional(),
  description: z.string().optional().nullable(),
  experience_level: z.array(z.string()).optional().nullable(),
  expires_at: z.string().optional().nullable(),
  id: z.string().optional(),
  is_archived: z.boolean().optional(),
  is_external: z.boolean().optional(),
  is_remote: z.boolean().optional(),
  job_type: z.string().optional().nullable(),
  location: z.string().optional().nullable(),
  published_at: z.string().optional().nullable(),
  salary_currency: z.string().optional().nullable(),
  salary_max: z.number().optional().nullable(),
  salary_min: z.number().optional().nullable(),
  search_vector: z.unknown().optional(),
  slug: z.string(),
  source_hash: z.string().optional().nullable(),
  source_url: z.string().optional().nullable(),
  status: publicJobStatusSchema.optional(),
  title: z.string(),
  updated_at: z.string().optional(),
});

export const publicJobListingsUpdateSchema = z.object({
  application_form_id: z.string().optional().nullable(),
  application_url: z.string().optional().nullable(),
  applications_count: z.number().optional(),
  archived_at: z.string().optional().nullable(),
  benefits_count: z.number().optional(),
  company_id: z.string().optional(),
  created_at: z.string().optional(),
  description: z.string().optional().nullable(),
  experience_level: z.array(z.string()).optional().nullable(),
  expires_at: z.string().optional().nullable(),
  id: z.string().optional(),
  is_archived: z.boolean().optional(),
  is_external: z.boolean().optional(),
  is_remote: z.boolean().optional(),
  job_type: z.string().optional().nullable(),
  location: z.string().optional().nullable(),
  published_at: z.string().optional().nullable(),
  salary_currency: z.string().optional().nullable(),
  salary_max: z.number().optional().nullable(),
  salary_min: z.number().optional().nullable(),
  search_vector: z.unknown().optional(),
  slug: z.string().optional(),
  source_hash: z.string().optional().nullable(),
  source_url: z.string().optional().nullable(),
  status: publicJobStatusSchema.optional(),
  title: z.string().optional(),
  updated_at: z.string().optional(),
});

export const publicJobListingsRelationshipsSchema = z.tuple([
  z.object({
    foreignKeyName: z.literal("job_listings_application_form_id_fkey"),
    columns: z.tuple([z.literal("application_form_id")]),
    isOneToOne: z.literal(false),
    referencedRelation: z.literal("forms"),
    referencedColumns: z.tuple([z.literal("id")]),
  }),
  z.object({
    foreignKeyName: z.literal("job_listings_company_id_fkey"),
    columns: z.tuple([z.literal("company_id")]),
    isOneToOne: z.literal(false),
    referencedRelation: z.literal("companies"),
    referencedColumns: z.tuple([z.literal("id")]),
  }),
]);

export const publicMatchesRowSchema = z.object({
  company_id: z.string(),
  created_at: z.string(),
  id: z.string(),
  last_notified_at: z.string().nullable(),
  overlap: z.array(z.string()),
  overlap_hash: z.string(),
  user_id: z.string(),
});

export const publicMatchesInsertSchema = z.object({
  company_id: z.string(),
  created_at: z.string().optional(),
  id: z.string().optional(),
  last_notified_at: z.string().optional().nullable(),
  overlap: z.array(z.string()).optional(),
  overlap_hash: z.string().optional(),
  user_id: z.string(),
});

export const publicMatchesUpdateSchema = z.object({
  company_id: z.string().optional(),
  created_at: z.string().optional(),
  id: z.string().optional(),
  last_notified_at: z.string().optional().nullable(),
  overlap: z.array(z.string()).optional(),
  overlap_hash: z.string().optional(),
  user_id: z.string().optional(),
});

export const publicMatchesRelationshipsSchema = z.tuple([
  z.object({
    foreignKeyName: z.literal("matches_company_id_fkey"),
    columns: z.tuple([z.literal("company_id")]),
    isOneToOne: z.literal(false),
    referencedRelation: z.literal("companies"),
    referencedColumns: z.tuple([z.literal("id")]),
  }),
]);

export const publicMessagesRowSchema = z.object({
  content: z.string(),
  conversation_id: z.string(),
  created_at: z.string(),
  id: z.string(),
  read_at: z.string().nullable(),
  sender_id: z.string(),
});

export const publicMessagesInsertSchema = z.object({
  content: z.string(),
  conversation_id: z.string(),
  created_at: z.string().optional(),
  id: z.string().optional(),
  read_at: z.string().optional().nullable(),
  sender_id: z.string(),
});

export const publicMessagesUpdateSchema = z.object({
  content: z.string().optional(),
  conversation_id: z.string().optional(),
  created_at: z.string().optional(),
  id: z.string().optional(),
  read_at: z.string().optional().nullable(),
  sender_id: z.string().optional(),
});

export const publicMessagesRelationshipsSchema = z.tuple([
  z.object({
    foreignKeyName: z.literal("messages_conversation_id_fkey"),
    columns: z.tuple([z.literal("conversation_id")]),
    isOneToOne: z.literal(false),
    referencedRelation: z.literal("conversations"),
    referencedColumns: z.tuple([z.literal("id")]),
  }),
]);

export const publicNewsletterSubscribersRowSchema = z.object({
  created_at: z.string(),
  email: z.string(),
  id: z.string(),
  is_active: z.boolean(),
  source: z.string().nullable(),
  unsubscribed_at: z.string().nullable(),
  updated_at: z.string(),
});

export const publicNewsletterSubscribersInsertSchema = z.object({
  created_at: z.string().optional(),
  email: z.string(),
  id: z.string().optional(),
  is_active: z.boolean().optional(),
  source: z.string().optional().nullable(),
  unsubscribed_at: z.string().optional().nullable(),
  updated_at: z.string().optional(),
});

export const publicNewsletterSubscribersUpdateSchema = z.object({
  created_at: z.string().optional(),
  email: z.string().optional(),
  id: z.string().optional(),
  is_active: z.boolean().optional(),
  source: z.string().optional().nullable(),
  unsubscribed_at: z.string().optional().nullable(),
  updated_at: z.string().optional(),
});

export const publicNotificationsRowSchema = z.object({
  body: z.string().nullable(),
  created_at: z.string(),
  data: jsonSchema.nullable(),
  id: z.string(),
  read_at: z.string().nullable(),
  title: z.string(),
  type: z.string(),
  user_id: z.string(),
});

export const publicNotificationsInsertSchema = z.object({
  body: z.string().optional().nullable(),
  created_at: z.string().optional(),
  data: jsonSchema.optional().nullable(),
  id: z.string().optional(),
  read_at: z.string().optional().nullable(),
  title: z.string(),
  type: z.string(),
  user_id: z.string(),
});

export const publicNotificationsUpdateSchema = z.object({
  body: z.string().optional().nullable(),
  created_at: z.string().optional(),
  data: jsonSchema.optional().nullable(),
  id: z.string().optional(),
  read_at: z.string().optional().nullable(),
  title: z.string().optional(),
  type: z.string().optional(),
  user_id: z.string().optional(),
});

export const publicProfileEducationRowSchema = z.object({
  created_at: z.string().nullable(),
  description: z.string().nullable(),
  end_year: z.number().nullable(),
  id: z.string(),
  institution: z.string(),
  is_current: z.boolean(),
  sort_order: z.number(),
  start_year: z.number().nullable(),
  title: z.string(),
  user_id: z.string(),
});

export const publicProfileEducationInsertSchema = z.object({
  created_at: z.string().optional().nullable(),
  description: z.string().optional().nullable(),
  end_year: z.number().optional().nullable(),
  id: z.string().optional(),
  institution: z.string(),
  is_current: z.boolean().optional(),
  sort_order: z.number().optional(),
  start_year: z.number().optional().nullable(),
  title: z.string(),
  user_id: z.string(),
});

export const publicProfileEducationUpdateSchema = z.object({
  created_at: z.string().optional().nullable(),
  description: z.string().optional().nullable(),
  end_year: z.number().optional().nullable(),
  id: z.string().optional(),
  institution: z.string().optional(),
  is_current: z.boolean().optional(),
  sort_order: z.number().optional(),
  start_year: z.number().optional().nullable(),
  title: z.string().optional(),
  user_id: z.string().optional(),
});

export const publicProfileEducationRelationshipsSchema = z.tuple([
  z.object({
    foreignKeyName: z.literal("profile_education_user_id_fkey"),
    columns: z.tuple([z.literal("user_id")]),
    isOneToOne: z.literal(false),
    referencedRelation: z.literal("profiles"),
    referencedColumns: z.tuple([z.literal("id")]),
  }),
]);

export const publicProfileExperienceRowSchema = z.object({
  company: z.string(),
  created_at: z.string().nullable(),
  description: z.string().nullable(),
  end_year: z.number().nullable(),
  id: z.string(),
  is_current: z.boolean(),
  sort_order: z.number(),
  start_year: z.number().nullable(),
  title: z.string(),
  user_id: z.string(),
});

export const publicProfileExperienceInsertSchema = z.object({
  company: z.string(),
  created_at: z.string().optional().nullable(),
  description: z.string().optional().nullable(),
  end_year: z.number().optional().nullable(),
  id: z.string().optional(),
  is_current: z.boolean().optional(),
  sort_order: z.number().optional(),
  start_year: z.number().optional().nullable(),
  title: z.string(),
  user_id: z.string(),
});

export const publicProfileExperienceUpdateSchema = z.object({
  company: z.string().optional(),
  created_at: z.string().optional().nullable(),
  description: z.string().optional().nullable(),
  end_year: z.number().optional().nullable(),
  id: z.string().optional(),
  is_current: z.boolean().optional(),
  sort_order: z.number().optional(),
  start_year: z.number().optional().nullable(),
  title: z.string().optional(),
  user_id: z.string().optional(),
});

export const publicProfileExperienceRelationshipsSchema = z.tuple([
  z.object({
    foreignKeyName: z.literal("profile_experience_user_id_fkey"),
    columns: z.tuple([z.literal("user_id")]),
    isOneToOne: z.literal(false),
    referencedRelation: z.literal("profiles"),
    referencedColumns: z.tuple([z.literal("id")]),
  }),
]);

export const publicProfileSkillsRowSchema = z.object({
  id: z.string(),
  skill_id: z.string(),
  sort_order: z.number(),
  user_id: z.string(),
});

export const publicProfileSkillsInsertSchema = z.object({
  id: z.string().optional(),
  skill_id: z.string(),
  sort_order: z.number().optional(),
  user_id: z.string(),
});

export const publicProfileSkillsUpdateSchema = z.object({
  id: z.string().optional(),
  skill_id: z.string().optional(),
  sort_order: z.number().optional(),
  user_id: z.string().optional(),
});

export const publicProfileSkillsRelationshipsSchema = z.tuple([
  z.object({
    foreignKeyName: z.literal("profile_skills_skill_id_fkey"),
    columns: z.tuple([z.literal("skill_id")]),
    isOneToOne: z.literal(false),
    referencedRelation: z.literal("skills"),
    referencedColumns: z.tuple([z.literal("id")]),
  }),
  z.object({
    foreignKeyName: z.literal("profile_skills_user_id_fkey"),
    columns: z.tuple([z.literal("user_id")]),
    isOneToOne: z.literal(false),
    referencedRelation: z.literal("profiles"),
    referencedColumns: z.tuple([z.literal("id")]),
  }),
]);

export const publicProfilesRowSchema = z.object({
  avatar_url: z.string().nullable(),
  bio: z.string().nullable(),
  completeness: z.number(),
  created_at: z.string(),
  cv_url: z.string().nullable(),
  experience_level: z.string().nullable(),
  full_name: z.string().nullable(),
  headline: z.string().nullable(),
  id: z.string(),
  is_public: z.boolean(),
  location: z.string().nullable(),
  notification_preferences: jsonSchema,
  notifications_browser: z.boolean(),
  notifications_email: z.boolean(),
  notifications_sms: z.boolean(),
  phone: z.string().nullable(),
  role: publicUserRoleSchema,
  slug: z.string().nullable(),
  updated_at: z.string(),
});

export const publicProfilesInsertSchema = z.object({
  avatar_url: z.string().optional().nullable(),
  bio: z.string().optional().nullable(),
  completeness: z.number().optional(),
  created_at: z.string().optional(),
  cv_url: z.string().optional().nullable(),
  experience_level: z.string().optional().nullable(),
  full_name: z.string().optional().nullable(),
  headline: z.string().optional().nullable(),
  id: z.string(),
  is_public: z.boolean().optional(),
  location: z.string().optional().nullable(),
  notification_preferences: jsonSchema.optional(),
  notifications_browser: z.boolean().optional(),
  notifications_email: z.boolean().optional(),
  notifications_sms: z.boolean().optional(),
  phone: z.string().optional().nullable(),
  role: publicUserRoleSchema.optional(),
  slug: z.string().optional().nullable(),
  updated_at: z.string().optional(),
});

export const publicProfilesUpdateSchema = z.object({
  avatar_url: z.string().optional().nullable(),
  bio: z.string().optional().nullable(),
  completeness: z.number().optional(),
  created_at: z.string().optional(),
  cv_url: z.string().optional().nullable(),
  experience_level: z.string().optional().nullable(),
  full_name: z.string().optional().nullable(),
  headline: z.string().optional().nullable(),
  id: z.string().optional(),
  is_public: z.boolean().optional(),
  location: z.string().optional().nullable(),
  notification_preferences: jsonSchema.optional(),
  notifications_browser: z.boolean().optional(),
  notifications_email: z.boolean().optional(),
  notifications_sms: z.boolean().optional(),
  phone: z.string().optional().nullable(),
  role: publicUserRoleSchema.optional(),
  slug: z.string().optional().nullable(),
  updated_at: z.string().optional(),
});

export const publicPushSubscriptionsRowSchema = z.object({
  auth: z.string(),
  created_at: z.string(),
  endpoint: z.string(),
  last_used_at: z.string().nullable(),
  p256dh: z.string(),
  user_agent: z.string().nullable(),
  user_id: z.string(),
});

export const publicPushSubscriptionsInsertSchema = z.object({
  auth: z.string(),
  created_at: z.string().optional(),
  endpoint: z.string(),
  last_used_at: z.string().optional().nullable(),
  p256dh: z.string(),
  user_agent: z.string().optional().nullable(),
  user_id: z.string(),
});

export const publicPushSubscriptionsUpdateSchema = z.object({
  auth: z.string().optional(),
  created_at: z.string().optional(),
  endpoint: z.string().optional(),
  last_used_at: z.string().optional().nullable(),
  p256dh: z.string().optional(),
  user_agent: z.string().optional().nullable(),
  user_id: z.string().optional(),
});

export const publicSkillsRowSchema = z.object({
  id: z.string(),
  is_approved: z.boolean(),
  name: z.string(),
});

export const publicSkillsInsertSchema = z.object({
  id: z.string().optional(),
  is_approved: z.boolean().optional(),
  name: z.string(),
});

export const publicSkillsUpdateSchema = z.object({
  id: z.string().optional(),
  is_approved: z.boolean().optional(),
  name: z.string().optional(),
});

export const publicAdminListUsersArgsSchema = z.never();

export const publicAdminListUsersReturnsSchema = z.array(
  z.object({
    avatar_url: z.string(),
    created_at: z.string(),
    email: z.string(),
    full_name: z.string(),
    id: z.string(),
    role: publicUserRoleSchema,
  }),
);

export const publicAdminSetSkillApprovalArgsSchema = z.object({
  p_is_approved: z.boolean(),
  p_skill_id: z.string(),
});

export const publicAdminSetSkillApprovalReturnsSchema = z.undefined();

export const publicAdminSetUserRoleArgsSchema = z.object({
  p_role: publicUserRoleSchema,
  p_user_id: z.string(),
});

export const publicAdminSetUserRoleReturnsSchema = z.undefined();

export const publicAlertsMatchingJobArgsSchema = z.object({
  _job_id: z.string(),
});

export const publicAlertsMatchingJobReturnsSchema = z.array(
  z.object({
    archived_at: z.string().nullable(),
    created_at: z.string(),
    filters: jsonSchema,
    frequency: publicAlertFrequencySchema,
    id: z.string(),
    is_active: z.boolean(),
    is_archived: z.boolean(),
    last_sent_at: z.string().nullable(),
    name: z.string(),
    user_id: z.string(),
  }),
);

export const publicApplicationNotificationRecipientArgsSchema = z.object({
  p_job_id: z.string(),
});

export const publicApplicationNotificationRecipientReturnsSchema = z.array(
  z.object({
    poster_email: z.string(),
    poster_name: z.string(),
    poster_user_id: z.string(),
  }),
);

export const publicCanSubmitFormResponseArgsSchema = z.object({
  p_form_id: z.string(),
  p_job_listing_id: z.string(),
});

export const publicCanSubmitFormResponseReturnsSchema = z.boolean();

export const publicClaimCompanyArgsSchema = z.object({
  p_code: z.string(),
  p_token: z.string(),
});

export const publicClaimCompanyReturnsSchema = z.array(
  z.object({
    company_id: z.string(),
    slug: z.string(),
  }),
);

export const publicCompanyHasNoOwnerArgsSchema = z.object({
  p_company_id: z.string(),
});

export const publicCompanyHasNoOwnerReturnsSchema = z.boolean();

export const publicIncrementCompanyEngagesArgsSchema = z.object({
  p_company_id: z.string(),
});

export const publicIncrementCompanyEngagesReturnsSchema = z.undefined();

export const publicIncrementCompanyVisitsArgsSchema = z.object({
  p_company_id: z.string(),
});

export const publicIncrementCompanyVisitsReturnsSchema = z.undefined();

export const publicIsCompanyMemberArgsSchema = z.object({
  p_company_id: z.string(),
  p_min_role: publicCompanyRoleSchema.optional(),
});

export const publicIsCompanyMemberReturnsSchema = z.boolean();

export const publicIssueCompanyClaimTokenArgsSchema = z.object({
  p_company_id: z.string(),
});

export const publicIssueCompanyClaimTokenReturnsSchema = z.array(
  z.object({
    code: z.string(),
    token: z.string(),
  }),
);

export const publicJobPosterRecipientArgsSchema = z.object({
  p_job_id: z.string(),
});

export const publicJobPosterRecipientReturnsSchema = z.array(
  z.object({
    poster_email: z.string(),
    poster_name: z.string(),
    poster_user_id: z.string(),
  }),
);

export const publicRecomputeProfileCompletenessArgsSchema = z.object({
  p_user_id: z.string(),
});

export const publicRecomputeProfileCompletenessReturnsSchema = z.number();

export const publicVerifyClaimCodeArgsSchema = z.object({
  p_code: z.string(),
  p_token: z.string(),
});

export const publicVerifyClaimCodeReturnsSchema = z.string();

export type PublicAlertFrequency = z.infer<typeof publicAlertFrequencySchema>;
export type PublicApplicationStatus = z.infer<
  typeof publicApplicationStatusSchema
>;
export type PublicCompanyRole = z.infer<typeof publicCompanyRoleSchema>;
export type PublicEntityType = z.infer<typeof publicEntityTypeSchema>;
export type PublicJobStatus = z.infer<typeof publicJobStatusSchema>;
export type PublicUserRole = z.infer<typeof publicUserRoleSchema>;
export type Json = z.infer<typeof jsonSchema>;
export type PublicAlertsRow = z.infer<typeof publicAlertsRowSchema>;
export type PublicAlertsInsert = z.infer<typeof publicAlertsInsertSchema>;
export type PublicAlertsUpdate = z.infer<typeof publicAlertsUpdateSchema>;
export type PublicAppReleaseAnnouncementsRow = z.infer<
  typeof publicAppReleaseAnnouncementsRowSchema
>;
export type PublicAppReleaseAnnouncementsInsert = z.infer<
  typeof publicAppReleaseAnnouncementsInsertSchema
>;
export type PublicAppReleaseAnnouncementsUpdate = z.infer<
  typeof publicAppReleaseAnnouncementsUpdateSchema
>;
export type PublicAppStateRow = z.infer<typeof publicAppStateRowSchema>;
export type PublicAppStateInsert = z.infer<typeof publicAppStateInsertSchema>;
export type PublicAppStateUpdate = z.infer<typeof publicAppStateUpdateSchema>;
export type PublicApplicationsRow = z.infer<typeof publicApplicationsRowSchema>;
export type PublicApplicationsInsert = z.infer<
  typeof publicApplicationsInsertSchema
>;
export type PublicApplicationsUpdate = z.infer<
  typeof publicApplicationsUpdateSchema
>;
export type PublicApplicationsRelationships = z.infer<
  typeof publicApplicationsRelationshipsSchema
>;
export type PublicBlogPostsRow = z.infer<typeof publicBlogPostsRowSchema>;
export type PublicBlogPostsInsert = z.infer<typeof publicBlogPostsInsertSchema>;
export type PublicBlogPostsUpdate = z.infer<typeof publicBlogPostsUpdateSchema>;
export type PublicBlogPostsRelationships = z.infer<
  typeof publicBlogPostsRelationshipsSchema
>;
export type PublicCompaniesRow = z.infer<typeof publicCompaniesRowSchema>;
export type PublicCompaniesInsert = z.infer<typeof publicCompaniesInsertSchema>;
export type PublicCompaniesUpdate = z.infer<typeof publicCompaniesUpdateSchema>;
export type PublicCompanyClaimNudgeLogRow = z.infer<
  typeof publicCompanyClaimNudgeLogRowSchema
>;
export type PublicCompanyClaimNudgeLogInsert = z.infer<
  typeof publicCompanyClaimNudgeLogInsertSchema
>;
export type PublicCompanyClaimNudgeLogUpdate = z.infer<
  typeof publicCompanyClaimNudgeLogUpdateSchema
>;
export type PublicCompanyClaimNudgeLogRelationships = z.infer<
  typeof publicCompanyClaimNudgeLogRelationshipsSchema
>;
export type PublicCompanyClaimTokensRow = z.infer<
  typeof publicCompanyClaimTokensRowSchema
>;
export type PublicCompanyClaimTokensInsert = z.infer<
  typeof publicCompanyClaimTokensInsertSchema
>;
export type PublicCompanyClaimTokensUpdate = z.infer<
  typeof publicCompanyClaimTokensUpdateSchema
>;
export type PublicCompanyClaimTokensRelationships = z.infer<
  typeof publicCompanyClaimTokensRelationshipsSchema
>;
export type PublicCompanyFavouritesRow = z.infer<
  typeof publicCompanyFavouritesRowSchema
>;
export type PublicCompanyFavouritesInsert = z.infer<
  typeof publicCompanyFavouritesInsertSchema
>;
export type PublicCompanyFavouritesUpdate = z.infer<
  typeof publicCompanyFavouritesUpdateSchema
>;
export type PublicCompanyFavouritesRelationships = z.infer<
  typeof publicCompanyFavouritesRelationshipsSchema
>;
export type PublicCompanySkillsRow = z.infer<
  typeof publicCompanySkillsRowSchema
>;
export type PublicCompanySkillsInsert = z.infer<
  typeof publicCompanySkillsInsertSchema
>;
export type PublicCompanySkillsUpdate = z.infer<
  typeof publicCompanySkillsUpdateSchema
>;
export type PublicCompanySkillsRelationships = z.infer<
  typeof publicCompanySkillsRelationshipsSchema
>;
export type PublicCompanyUsersRow = z.infer<typeof publicCompanyUsersRowSchema>;
export type PublicCompanyUsersInsert = z.infer<
  typeof publicCompanyUsersInsertSchema
>;
export type PublicCompanyUsersUpdate = z.infer<
  typeof publicCompanyUsersUpdateSchema
>;
export type PublicCompanyUsersRelationships = z.infer<
  typeof publicCompanyUsersRelationshipsSchema
>;
export type PublicContactInfoRow = z.infer<typeof publicContactInfoRowSchema>;
export type PublicContactInfoInsert = z.infer<
  typeof publicContactInfoInsertSchema
>;
export type PublicContactInfoUpdate = z.infer<
  typeof publicContactInfoUpdateSchema
>;
export type PublicConversationParticipantsRow = z.infer<
  typeof publicConversationParticipantsRowSchema
>;
export type PublicConversationParticipantsInsert = z.infer<
  typeof publicConversationParticipantsInsertSchema
>;
export type PublicConversationParticipantsUpdate = z.infer<
  typeof publicConversationParticipantsUpdateSchema
>;
export type PublicConversationParticipantsRelationships = z.infer<
  typeof publicConversationParticipantsRelationshipsSchema
>;
export type PublicConversationsRow = z.infer<
  typeof publicConversationsRowSchema
>;
export type PublicConversationsInsert = z.infer<
  typeof publicConversationsInsertSchema
>;
export type PublicConversationsUpdate = z.infer<
  typeof publicConversationsUpdateSchema
>;
export type PublicFaqRow = z.infer<typeof publicFaqRowSchema>;
export type PublicFaqInsert = z.infer<typeof publicFaqInsertSchema>;
export type PublicFaqUpdate = z.infer<typeof publicFaqUpdateSchema>;
export type PublicFavoritesRow = z.infer<typeof publicFavoritesRowSchema>;
export type PublicFavoritesInsert = z.infer<typeof publicFavoritesInsertSchema>;
export type PublicFavoritesUpdate = z.infer<typeof publicFavoritesUpdateSchema>;
export type PublicFavoritesRelationships = z.infer<
  typeof publicFavoritesRelationshipsSchema
>;
export type PublicFormFieldsRow = z.infer<typeof publicFormFieldsRowSchema>;
export type PublicFormFieldsInsert = z.infer<
  typeof publicFormFieldsInsertSchema
>;
export type PublicFormFieldsUpdate = z.infer<
  typeof publicFormFieldsUpdateSchema
>;
export type PublicFormFieldsRelationships = z.infer<
  typeof publicFormFieldsRelationshipsSchema
>;
export type PublicFormResponseValuesRow = z.infer<
  typeof publicFormResponseValuesRowSchema
>;
export type PublicFormResponseValuesInsert = z.infer<
  typeof publicFormResponseValuesInsertSchema
>;
export type PublicFormResponseValuesUpdate = z.infer<
  typeof publicFormResponseValuesUpdateSchema
>;
export type PublicFormResponseValuesRelationships = z.infer<
  typeof publicFormResponseValuesRelationshipsSchema
>;
export type PublicFormResponsesRow = z.infer<
  typeof publicFormResponsesRowSchema
>;
export type PublicFormResponsesInsert = z.infer<
  typeof publicFormResponsesInsertSchema
>;
export type PublicFormResponsesUpdate = z.infer<
  typeof publicFormResponsesUpdateSchema
>;
export type PublicFormResponsesRelationships = z.infer<
  typeof publicFormResponsesRelationshipsSchema
>;
export type PublicFormsRow = z.infer<typeof publicFormsRowSchema>;
export type PublicFormsInsert = z.infer<typeof publicFormsInsertSchema>;
export type PublicFormsUpdate = z.infer<typeof publicFormsUpdateSchema>;
export type PublicFormsRelationships = z.infer<
  typeof publicFormsRelationshipsSchema
>;
export type PublicJobBenefitsRow = z.infer<typeof publicJobBenefitsRowSchema>;
export type PublicJobBenefitsInsert = z.infer<
  typeof publicJobBenefitsInsertSchema
>;
export type PublicJobBenefitsUpdate = z.infer<
  typeof publicJobBenefitsUpdateSchema
>;
export type PublicJobBenefitsRelationships = z.infer<
  typeof publicJobBenefitsRelationshipsSchema
>;
export type PublicJobListingsRow = z.infer<typeof publicJobListingsRowSchema>;
export type PublicJobListingsInsert = z.infer<
  typeof publicJobListingsInsertSchema
>;
export type PublicJobListingsUpdate = z.infer<
  typeof publicJobListingsUpdateSchema
>;
export type PublicJobListingsRelationships = z.infer<
  typeof publicJobListingsRelationshipsSchema
>;
export type PublicMatchesRow = z.infer<typeof publicMatchesRowSchema>;
export type PublicMatchesInsert = z.infer<typeof publicMatchesInsertSchema>;
export type PublicMatchesUpdate = z.infer<typeof publicMatchesUpdateSchema>;
export type PublicMatchesRelationships = z.infer<
  typeof publicMatchesRelationshipsSchema
>;
export type PublicMessagesRow = z.infer<typeof publicMessagesRowSchema>;
export type PublicMessagesInsert = z.infer<typeof publicMessagesInsertSchema>;
export type PublicMessagesUpdate = z.infer<typeof publicMessagesUpdateSchema>;
export type PublicMessagesRelationships = z.infer<
  typeof publicMessagesRelationshipsSchema
>;
export type PublicNewsletterSubscribersRow = z.infer<
  typeof publicNewsletterSubscribersRowSchema
>;
export type PublicNewsletterSubscribersInsert = z.infer<
  typeof publicNewsletterSubscribersInsertSchema
>;
export type PublicNewsletterSubscribersUpdate = z.infer<
  typeof publicNewsletterSubscribersUpdateSchema
>;
export type PublicNotificationsRow = z.infer<
  typeof publicNotificationsRowSchema
>;
export type PublicNotificationsInsert = z.infer<
  typeof publicNotificationsInsertSchema
>;
export type PublicNotificationsUpdate = z.infer<
  typeof publicNotificationsUpdateSchema
>;
export type PublicProfileEducationRow = z.infer<
  typeof publicProfileEducationRowSchema
>;
export type PublicProfileEducationInsert = z.infer<
  typeof publicProfileEducationInsertSchema
>;
export type PublicProfileEducationUpdate = z.infer<
  typeof publicProfileEducationUpdateSchema
>;
export type PublicProfileEducationRelationships = z.infer<
  typeof publicProfileEducationRelationshipsSchema
>;
export type PublicProfileExperienceRow = z.infer<
  typeof publicProfileExperienceRowSchema
>;
export type PublicProfileExperienceInsert = z.infer<
  typeof publicProfileExperienceInsertSchema
>;
export type PublicProfileExperienceUpdate = z.infer<
  typeof publicProfileExperienceUpdateSchema
>;
export type PublicProfileExperienceRelationships = z.infer<
  typeof publicProfileExperienceRelationshipsSchema
>;
export type PublicProfileSkillsRow = z.infer<
  typeof publicProfileSkillsRowSchema
>;
export type PublicProfileSkillsInsert = z.infer<
  typeof publicProfileSkillsInsertSchema
>;
export type PublicProfileSkillsUpdate = z.infer<
  typeof publicProfileSkillsUpdateSchema
>;
export type PublicProfileSkillsRelationships = z.infer<
  typeof publicProfileSkillsRelationshipsSchema
>;
export type PublicProfilesRow = z.infer<typeof publicProfilesRowSchema>;
export type PublicProfilesInsert = z.infer<typeof publicProfilesInsertSchema>;
export type PublicProfilesUpdate = z.infer<typeof publicProfilesUpdateSchema>;
export type PublicPushSubscriptionsRow = z.infer<
  typeof publicPushSubscriptionsRowSchema
>;
export type PublicPushSubscriptionsInsert = z.infer<
  typeof publicPushSubscriptionsInsertSchema
>;
export type PublicPushSubscriptionsUpdate = z.infer<
  typeof publicPushSubscriptionsUpdateSchema
>;
export type PublicSkillsRow = z.infer<typeof publicSkillsRowSchema>;
export type PublicSkillsInsert = z.infer<typeof publicSkillsInsertSchema>;
export type PublicSkillsUpdate = z.infer<typeof publicSkillsUpdateSchema>;
export type PublicAdminListUsersArgs = z.infer<
  typeof publicAdminListUsersArgsSchema
>;
export type PublicAdminListUsersReturns = z.infer<
  typeof publicAdminListUsersReturnsSchema
>;
export type PublicAdminSetSkillApprovalArgs = z.infer<
  typeof publicAdminSetSkillApprovalArgsSchema
>;
export type PublicAdminSetSkillApprovalReturns = z.infer<
  typeof publicAdminSetSkillApprovalReturnsSchema
>;
export type PublicAdminSetUserRoleArgs = z.infer<
  typeof publicAdminSetUserRoleArgsSchema
>;
export type PublicAdminSetUserRoleReturns = z.infer<
  typeof publicAdminSetUserRoleReturnsSchema
>;
export type PublicAlertsMatchingJobArgs = z.infer<
  typeof publicAlertsMatchingJobArgsSchema
>;
export type PublicAlertsMatchingJobReturns = z.infer<
  typeof publicAlertsMatchingJobReturnsSchema
>;
export type PublicApplicationNotificationRecipientArgs = z.infer<
  typeof publicApplicationNotificationRecipientArgsSchema
>;
export type PublicApplicationNotificationRecipientReturns = z.infer<
  typeof publicApplicationNotificationRecipientReturnsSchema
>;
export type PublicCanSubmitFormResponseArgs = z.infer<
  typeof publicCanSubmitFormResponseArgsSchema
>;
export type PublicCanSubmitFormResponseReturns = z.infer<
  typeof publicCanSubmitFormResponseReturnsSchema
>;
export type PublicClaimCompanyArgs = z.infer<
  typeof publicClaimCompanyArgsSchema
>;
export type PublicClaimCompanyReturns = z.infer<
  typeof publicClaimCompanyReturnsSchema
>;
export type PublicCompanyHasNoOwnerArgs = z.infer<
  typeof publicCompanyHasNoOwnerArgsSchema
>;
export type PublicCompanyHasNoOwnerReturns = z.infer<
  typeof publicCompanyHasNoOwnerReturnsSchema
>;
export type PublicIncrementCompanyEngagesArgs = z.infer<
  typeof publicIncrementCompanyEngagesArgsSchema
>;
export type PublicIncrementCompanyEngagesReturns = z.infer<
  typeof publicIncrementCompanyEngagesReturnsSchema
>;
export type PublicIncrementCompanyVisitsArgs = z.infer<
  typeof publicIncrementCompanyVisitsArgsSchema
>;
export type PublicIncrementCompanyVisitsReturns = z.infer<
  typeof publicIncrementCompanyVisitsReturnsSchema
>;
export type PublicIsCompanyMemberArgs = z.infer<
  typeof publicIsCompanyMemberArgsSchema
>;
export type PublicIsCompanyMemberReturns = z.infer<
  typeof publicIsCompanyMemberReturnsSchema
>;
export type PublicIssueCompanyClaimTokenArgs = z.infer<
  typeof publicIssueCompanyClaimTokenArgsSchema
>;
export type PublicIssueCompanyClaimTokenReturns = z.infer<
  typeof publicIssueCompanyClaimTokenReturnsSchema
>;
export type PublicJobPosterRecipientArgs = z.infer<
  typeof publicJobPosterRecipientArgsSchema
>;
export type PublicJobPosterRecipientReturns = z.infer<
  typeof publicJobPosterRecipientReturnsSchema
>;
export type PublicRecomputeProfileCompletenessArgs = z.infer<
  typeof publicRecomputeProfileCompletenessArgsSchema
>;
export type PublicRecomputeProfileCompletenessReturns = z.infer<
  typeof publicRecomputeProfileCompletenessReturnsSchema
>;
export type PublicVerifyClaimCodeArgs = z.infer<
  typeof publicVerifyClaimCodeArgsSchema
>;
export type PublicVerifyClaimCodeReturns = z.infer<
  typeof publicVerifyClaimCodeReturnsSchema
>;
